- properly search for gnumed.py in list of paths

diff --git a/gnumed/gnumed/dists/Linux/gnumed b/gnumed/gnumed/dists/Linux/gnumed
--- a/gnumed/gnumed/dists/Linux/gnumed
+++ b/gnumed/gnumed/dists/Linux/gnumed
@@ -6,7 +6,7 @@
 # client.
 #
 # $Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gnumed/dists/Linux/gnumed,v $
-# $Id: gnumed,v 1.14 2008-08-01 10:32:41 ncq Exp $
+# $Id: gnumed,v 1.14.2.1 2008-08-31 22:21:22 ncq Exp $
 # license: GPL
 # Karsten Hilbert, Sebastian Hilbert, Andreas Tille
 #--------------------------------------------------
@@ -49,15 +49,25 @@ PYVER=`python -c 'import sys; print sys.version[:3]'`
 #		grep -q PCLinuxOS /etc/version
 #		if [ $? -eq 0 ] ; then
 GNUMED_SCRIPT_PATH_CANDIDATES=\
-"/var/lib/python-support/python${PYVER}/Gnumed/wxpython"\ 
-"/usr/lib/python${PYVER}/site-packages/Gnumed/wxpython"\ 
-"/usr/lib64/python${PYVER}/site-packages/Gnumed/wxpython"
+"/var/lib/python-support/python${PYVER}/Gnumed/wxpython"\
+" /usr/lib/python${PYVER}/site-packages/Gnumed/wxpython"\
+" /usr/lib64/python${PYVER}/site-packages/Gnumed/wxpython"
 
-for GNUMED_SCRIPT_PATH in "${GNUMED_SCRIPT_PATH_CANDIDATES}" ; do
-	if [ -f ${GNUMED_SCRIPT_PATH}/gnumed.py ] ; then
+GM_SCRIPT=""
+for GNUMED_SCRIPT_PATH in ${GNUMED_SCRIPT_PATH_CANDIDATES} ; do
+	if test -f ${GNUMED_SCRIPT_PATH}/gnumed.py ; then
+		GM_SCRIPT="${GNUMED_SCRIPT_PATH}/gnumed.py"
 		break
 	fi
 done
+
+if test -z "${GM_SCRIPT}" ; then
+	echo "Cannot find \"gnumed.py\" in any of:"
+	for GNUMED_SCRIPT_PATH in ${GNUMED_SCRIPT_PATH_CANDIDATES} ; do
+		echo " ${GNUMED_SCRIPT_PATH}"
+	done
+	exit 1
+fi
 
 
 # check for explicit --conf-file option
@@ -90,7 +100,10 @@ python ${GNUMED_SCRIPT_PATH}/gnumed.py ${CONFFILE} ${OPTIONS}
 
 #==================================================
 # $Log: gnumed,v $
-# Revision 1.14  2008-08-01 10:32:41  ncq
+# Revision 1.14.2.1  2008-08-31 22:21:22  ncq
+# - properly search for gnumed.py in list of paths
+#
+# Revision 1.14  2008/08/01 10:32:41  ncq
 # - /bin/sh -> /bin/bash
 #
 # Revision 1.13  2008/07/22 13:55:58  ncq
