- cleanup - support a few pathes for gnumed.py, included from downstream packages

diff --git a/gnumed/gnumed/dists/Linux/gnumed b/gnumed/gnumed/dists/Linux/gnumed
--- a/gnumed/gnumed/dists/Linux/gnumed
+++ b/gnumed/gnumed/dists/Linux/gnumed
@@ -6,7 +6,7 @@
 # client.
 #
 # $Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gnumed/dists/Linux/gnumed,v $
-# $Id: gnumed,v 1.10 2008-01-01 13:53:35 ncq Exp $
+# $Id: gnumed,v 1.11 2008-02-25 17:44:55 ncq Exp $
 # license: GPL
 # Karsten Hilbert, Sebastian Hilbert, Andreas Tille
 #--------------------------------------------------
@@ -24,6 +24,7 @@ if echo $name | grep -q -- "-debug" ; then
 	OPTIONS="$OPTIONS --debug"
 fi
 
+
 # The system-wide configuration file for backend profiles.
 SYSCONF="/etc/gnumed/gnumed-client.conf"
 if [ ! -e ${SYSCONF} ] ; then
@@ -31,10 +32,6 @@ if [ ! -e ${SYSCONF} ] ; then
 	exit 1
 fi
 
-# There has to be a user config file (even if empty).
-#if [ ! -e ${HOME}/.gnumed/${name}.conf ] ; then
-#	touch ${HOME}/.gnumed/${name}.conf
-#fi
 
 ## Different ways to obtain the version number of the running Python interpreter
 ## store this here just for the purpose of education :-)
@@ -43,8 +40,25 @@ fi
 # PYVER=`python -c 'import platform; print platform.python_version()'`
 PYVER=`python -c 'import sys; print sys.version[:3]'`
 
+
 # this is where the gnumed.py Python script actually lives
+# Debian is our reference platform
 GNUMEDDIR=/var/lib/python-support/python${PYVER}/Gnumed/wxpython
+# SuSE
+if [ -f /etc/SuSE-release ] ; then
+	GNUMEDDIR=/usr/lib/python${PYVER}/site-packages/Gnumed/wxpython
+fi
+# PCLinuxOS
+if [ -f /etc/version ] ; then
+	grep -q PCLinuxOS /etc/version
+	if [ $? -eq 0 ] ; then
+		GNUMEDDIR=/usr/lib/python${PYVER}/site-packages/Gnumed/wxpython
+	fi
+fi
+# Mandriva
+#if [ -f /etc/mandriva-release ] ; then
+#fi
+
 
 # check for explicit --conf-file option
 CONFFILE=""
@@ -73,7 +87,11 @@ python ${GNUMEDDIR}/gnumed.py ${CONFFILE} ${OPTIONS}
 
 #==================================================
 # $Log: gnumed,v $
-# Revision 1.10  2008-01-01 13:53:35  ncq
+# Revision 1.11  2008-02-25 17:44:55  ncq
+# - cleanup
+# - support a few pathes for gnumed.py, included from downstream packages
+#
+# Revision 1.10  2008/01/01 13:53:35  ncq
 # - should not need touching user config file anymore
 #
 # Revision 1.9  2007/09/24 18:37:45  ncq
