Replace gtklp with okular
	Gtklp is no more. Use okular as last-ditch resort.
	Printable file types are limited though.

(cherry picked from commit 54447b92d74088e8c9ad9d8977082bc491f71dca)

diff --git a/gnumed/gnumed/external-tools/gm-print_doc b/gnumed/gnumed/external-tools/gm-print_doc
--- a/gnumed/gnumed/external-tools/gm-print_doc
+++ b/gnumed/gnumed/external-tools/gm-print_doc
@@ -72,16 +72,18 @@ fi
 
 # generic badness ?
 if [ "${CALL_PRINTER_MANAGER}" = "" ]; then
-	A=`which acroread`
+#	A=`which acroread`
+	A=`which okular`
 	if [ $? = 0 ]; then
-		CALL_PRINTER_MANAGER="acroread ${FILES}"
+#		CALL_PRINTER_MANAGER="acroread ${FILES}"
+		CALL_PRINTER_MANAGER="okular --print-and-exit ${FILES}"
 	fi
 fi
 
 # nothing found ?
 if [ "${CALL_PRINTER_MANAGER}" = "" ]; then
 	echo ""
-	echo "Cannot find any of kprinter, gtklp, MacOSX/Darwin, or acroread."
+	echo "Cannot find any of kprinter, gtklp, MacOSX/Darwin, or okular."
 	echo "Cannot print document(s)."
 	echo ""
 	exit 127
